### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-localstorage-intro#2]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://limping-pain.surge.sh) and meets the following [project](http://lansingcodelab.com/lessons/localstorage-intro/1) criteria:
- [x] Builds off a previous project
- [x] Includes a button, which when clicked, will toggle the website between day and night mode by changing the class on the body with `document.body.className = 'some-class-name'`
- [x] When in day mode, the background of the website is bright, with a darker color for the text
- [x] When in night mode, the background of the website is a very dark color, with a brighter color for the text
- [x] When a user changes the theme, their choice is remembered and the appropriate color theme is shown on every subsequent visit
- [x] Somewhere on the page, the user is told how many times they've visited a page on the website

and a reset button, and a fancy toggle switch!

**Comment by chrisvfritz** [comment]
![i can has shipit?](http://cdn.meme.am/instances/500x/63350567.jpg)

u can haz :shipit:
